[tool.poetry]
name = "iceberg"
version = "0.0.1"
description = "Plex torrent streaming through Real Debrid and 3rd party services like Overseerr, Mdblist, etc."
authors = ["Iceberg Developers"]
license = "GPL-3.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
dill = "^0.3.8"
plexapi = "^4.15.10"
requests = "^2.31.0"
xmltodict = "^0.13.0"
lxml = "^5.1.0"
pathos = "^0.3.2"
pydantic = "^2.6.3"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.27.1"}
parse-torrent-title = "^2.8.1"
thefuzz = "^0.22.1"
apscheduler = "^3.10.4"
watchdog = "^4.0.0"
coverage = "^7.4.3"
deepdiff = "^6.7.1"
pyright = "^1.1.352"
ruff = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
